# Generated by Django 3.0.1 on 2020-01-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=191)),
                ('last_name', models.CharField(max_length=191)),
                ('sirname', models.CharField(max_length=191)),
                ('profile_photo', models.ImageField(upload_to='Student_profile')),
                ('adm_number', models.CharField(max_length=191)),
                ('accademic_year', models.CharField(max_length=191)),
                ('school', models.CharField(max_length=191)),
                ('study_method', models.CharField(max_length=191)),
                ('year_of_study', models.CharField(max_length=191)),
                ('programme', models.CharField(max_length=191)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
