# Generated by Django 3.0.1 on 2020-01-31 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examcard', '0002_studentunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=191)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.RemoveField(
            model_name='studentunit',
            name='unit',
        ),
        migrations.AddField(
            model_name='studentunit',
            name='student_unit',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='examcard.Unit'),
            preserve_default=False,
        ),
    ]
