# Generated by Django 3.0.1 on 2020-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcard', '0005_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
