# Generated by Django 3.0.1 on 2020-01-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examcard', '0006_auto_20200131_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='student',
            new_name='profile',
        ),
    ]
