# Generated by Django 3.0.1 on 2020-02-02 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examcard', '0008_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='timstamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
