# Generated by Django 3.0.1 on 2020-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcard', '0011_auto_20200202_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.TextField(),
        ),
    ]
