# Generated by Django 3.0.1 on 2020-01-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=191)),
                ('adm_number', models.CharField(max_length=191)),
                ('exam_card_number', models.CharField(max_length=6)),
                ('fee', models.BooleanField(default=True, null=True)),
                ('qr_code', models.ImageField(upload_to='QRs')),
            ],
        ),
    ]
