# Generated by Django 3.0.1 on 2020-01-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autogen',
            name='qr_code',
        ),
    ]
